# Generated by Django 3.1 on 2020-10-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(default="Hello, i'm new to ConnectedIn"),
        ),
    ]
